[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# [[keyboard.bindings]]
# key = "H"
# mods = "Alt"
# action = "SendString"
# chars = "\u001bh"
#
# [[keyboard.bindings]]
# key = "L"
# mods = "Alt"
# action = "SendString"
# chars = "\u001bl"
